### ISSUE TITLE
I am getting this error whenever i am running python teaser_python_3dsmooth.py. pls help

### ISSUE THREAD

**Issue by GKarthikn92** [MIT-SPARK/TEASER-plusplus#169]
~/TEASER-plusplus/examples/teaser_python_3dsmooth$ python teaser_python_3dsmooth.py
Traceback (most recent call last):
  File "teaser_python_3dsmooth.py", line 7, in <module>
    from sklearn.neighbors import KDTree
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/sklearn/utils/validation.py", line 26, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/scipy/stats/__init__.py", line 348, in <module>
    from .stats import *
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/scipy/stats/stats.py", line 175, in <module>
    import scipy.special as special
  File "/home/karthik/anaconda3/envs/teaser_test/lib/python3.6/site-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory

**Comment by LimHyungTae** [comment]
There's little information, but could you please run `sudo ldconfig`? This error does not occur from our codes
