### ISSUE TITLE
teaser_python_3dsmooth example

### ISSUE THREAD

**Issue by hamid54** [MIT-SPARK/TEASER-plusplus#75]
Hi,
teaser_python_3dsmooth example does not work. I have a ubuntu 20.04. I followed the given instruction but when I ran teaser_python_3dsmooth, first it asked for pandas and flyfile packages, and then it gave me this error: 
`Traceback (most recent call last):
  File "teaser_python_3dsmooth.py", line 345, in <module>
    scene_path, desc_path, gt_mat, pair[0], pair[1]
  File "teaser_python_3dsmooth.py", line 267, in pair_eval_helper
    frag1 = o3d.registration.Feature()
AttributeError: module 'open3d' has no attribute 'registration'
`

It seems like there is a version conflict there.  By the way, teaser_cpp_ply and teaser_python_ply are running without any problem.  Thank you!

Hamid

**The whole script:**
```
$ conda create -n teaser python=3.6 numpy
Collecting package metadata (current_repodata.json): done
Solving environment: done

** Package Plan **

  environment location: ~/anaconda3/envs/teaser

  added / updated specs:
    - numpy
    - python=3.6


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  blas               pkgs/main/linux-64::blas-1.0-mkl
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.1.19-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2020.12.5-py36h06a4308_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.2-254
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  mkl                pkgs/main/linux-64::mkl-2020.2-256
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py36he8ac12f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.2.0-py36h23d657b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.1-py36h0573a6f_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  numpy              pkgs/main/linux-64::numpy-1.19.2-py36h54aff64_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.19.2-py36hfa32c7d_0
  openssl            pkgs/main/linux-64::openssl-1.1.1i-h27cfd23_0
  pip                pkgs/main/linux-64::pip-20.3.3-py36h06a4308_0
  python             pkgs/main/linux-64::python-3.6.12-hcff3b4d_2
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py36h06a4308_0
  six                pkgs/main/linux-64::six-1.15.0-py36h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
*
* To activate this environment, use
*
*     $ conda activate teaser
*
* To deactivate an active environment, use
*
*     $ conda deactivate

(base) ~/Projects$ conda activate teaser
(teaser) ~/Projects$ conda install -c open3d-admin open3d=0.9.0.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

** Package Plan **

  environment location: ~/anaconda3/envs/teaser

  added / updated specs:
    - open3d=0.9.0.0


The following NEW packages will be INSTALLED:

  argon2-cffi        pkgs/main/linux-64::argon2-cffi-20.1.0-py36h7b6447c_1
  async_generator    pkgs/main/linux-64::async_generator-1.10-py36h28b3542_0
  attrs              pkgs/main/noarch::attrs-20.3.0-pyhd3eb1b0_0
  backcall           pkgs/main/noarch::backcall-0.2.0-py_0
  bleach             pkgs/main/noarch::bleach-3.2.2-pyhd3eb1b0_0
  cffi               pkgs/main/linux-64::cffi-1.14.4-py36h261ae71_0
  decorator          pkgs/main/noarch::decorator-4.4.2-py_0
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  entrypoints        pkgs/main/linux-64::entrypoints-0.3-py36_0
  importlib-metadata pkgs/main/noarch::importlib-metadata-2.0.0-py_1
  importlib_metadata pkgs/main/noarch::importlib_metadata-2.0.0-1
  ipykernel          pkgs/main/linux-64::ipykernel-5.3.4-py36h5ca1d4c_0
  ipython            pkgs/main/linux-64::ipython-7.16.1-py36h5ca1d4c_0
  ipython_genutils   pkgs/main/noarch::ipython_genutils-0.2.0-pyhd3eb1b0_1
  ipywidgets         pkgs/main/noarch::ipywidgets-7.6.3-pyhd3eb1b0_1
  jedi               pkgs/main/linux-64::jedi-0.18.0-py36h06a4308_1
  jinja2             pkgs/main/noarch::jinja2-2.11.2-pyhd3eb1b0_0
  jsonschema         pkgs/main/noarch::jsonschema-3.2.0-py_2
  jupyter_client     pkgs/main/noarch::jupyter_client-6.1.7-py_0
  jupyter_core       pkgs/main/linux-64::jupyter_core-4.7.0-py36h06a4308_0
  jupyterlab_pygmen~ pkgs/main/noarch::jupyterlab_pygments-0.1.2-py_0
  jupyterlab_widgets pkgs/main/noarch::jupyterlab_widgets-1.0.0-pyhd3eb1b0_1
  libsodium          pkgs/main/linux-64::libsodium-1.0.18-h7b6447c_0
  markupsafe         pkgs/main/linux-64::markupsafe-1.1.1-py36h7b6447c_0
  mistune            pkgs/main/linux-64::mistune-0.8.4-py36h7b6447c_0
  nbclient           pkgs/main/noarch::nbclient-0.5.1-py_0
  nbconvert          pkgs/main/linux-64::nbconvert-6.0.7-py36_0
  nbformat           pkgs/main/noarch::nbformat-5.1.2-pyhd3eb1b0_1
  nest-asyncio       pkgs/main/noarch::nest-asyncio-1.4.3-pyhd3eb1b0_0
  notebook           pkgs/main/linux-64::notebook-6.2.0-py36h06a4308_0
  open3d             open3d-admin/linux-64::open3d-0.9.0.0-py36_0
  packaging          pkgs/main/noarch::packaging-20.8-pyhd3eb1b0_0
  pandoc             pkgs/main/linux-64::pandoc-2.11-hb0f4dca_0
  pandocfilters      pkgs/main/linux-64::pandocfilters-1.4.3-py36h06a4308_1
  parso              pkgs/main/noarch::parso-0.8.1-pyhd3eb1b0_0
  pexpect            pkgs/main/noarch::pexpect-4.8.0-pyhd3eb1b0_3
  pickleshare        pkgs/main/noarch::pickleshare-0.7.5-pyhd3eb1b0_1003
  prometheus_client  pkgs/main/noarch::prometheus_client-0.9.0-pyhd3eb1b0_0
  prompt-toolkit     pkgs/main/noarch::prompt-toolkit-3.0.8-py_0
  ptyprocess         pkgs/main/noarch::ptyprocess-0.7.0-pyhd3eb1b0_2
  pycparser          pkgs/main/noarch::pycparser-2.20-py_2
  pygments           pkgs/main/noarch::pygments-2.7.4-pyhd3eb1b0_0
  pyparsing          pkgs/main/noarch::pyparsing-2.4.7-pyhd3eb1b0_0
  pyrsistent         pkgs/main/linux-64::pyrsistent-0.17.3-py36h7b6447c_0
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pyzmq              pkgs/main/linux-64::pyzmq-20.0.0-py36h2531618_1
  send2trash         pkgs/main/noarch::send2trash-1.5.0-pyhd3eb1b0_1
  terminado          pkgs/main/linux-64::terminado-0.9.2-py36h06a4308_0
  testpath           pkgs/main/noarch::testpath-0.4.4-py_0
  tornado            pkgs/main/linux-64::tornado-6.1-py36h27cfd23_0
  traitlets          pkgs/main/linux-64::traitlets-4.3.3-py36_0
  wcwidth            pkgs/main/noarch::wcwidth-0.2.5-py_0
  webencodings       pkgs/main/linux-64::webencodings-0.5.1-py36_1
  widgetsnbextension pkgs/main/linux-64::widgetsnbextension-3.5.1-py36_0
  zeromq             pkgs/main/linux-64::zeromq-4.3.3-he6710b0_3
  zipp               pkgs/main/noarch::zipp-3.4.0-pyhd3eb1b0_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(teaser) ~/Projects$ conda install scikit-learn
Collecting package metadata (current_repodata.json): done
Solving environment: done

** Package Plan **

  environment location: ~/anaconda3/envs/teaser

  added / updated specs:
    - scikit-learn


The following NEW packages will be INSTALLED:

  joblib             pkgs/main/noarch::joblib-1.0.0-pyhd3eb1b0_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  scikit-learn       pkgs/main/linux-64::scikit-learn-0.23.2-py36h0573a6f_0
  scipy              pkgs/main/linux-64::scipy-1.5.2-py36h0b6359f_0
  threadpoolctl      pkgs/main/noarch::threadpoolctl-2.1.0-pyh5ca1d4c_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(teaser) ~/Projects$ mkdir Teaser-py
(teaser) ~/Projects$ cd Teaser-py/
(teaser) ~/Projects/Teaser-py$ git clone https://github.com/MIT-SPARK/TEASER-plusplus.git
Cloning into 'TEASER-plusplus'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 620 (delta 29), reused 48 (delta 21), pack-reused 543
Receiving objects: 100% (620/620), 30.27 MiB | 13.00 MiB/s, done.
Resolving deltas: 100% (210/210), done.
(teaser) ~/Projects/Teaser-py$ cd TEASER-plusplus && mkdir build && cd build
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/build$ cmake -DTEASERPP_PYTHON_VERSION=3.6 .. && make teaserpp_python
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Enable printing of diagnostic messages.
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Projects/Teaser-py/TEASER-plusplus/build/googletest-download
Scanning dependencies of target googletest
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (download, verify and extract) for 'googletest'
-- Downloading...
   dst='~/Projects/Teaser-py/TEASER-plusplus/build/googletest-download/googletest-prefix/src/release-1.8.1.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/google/googletest/archive/release-1.8.1.zip'
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 7% complete]
-- [download 10% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 20% complete]
-- [download 26% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 35% complete]
-- [download 37% complete]
-- [download 40% complete]
-- [download 45% complete]
-- [download 56% complete]
-- [download 61% complete]
-- [download 63% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 73% complete]
-- [download 76% complete]
-- [download 78% complete]
-- [download 82% complete]
-- [download 85% complete]
-- [download 87% complete]
-- [download 89% complete]
-- [download 91% complete]
-- [download 94% complete]
-- [download 96% complete]
-- [download 98% complete]
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='~/Projects/Teaser-py/TEASER-plusplus/build/googletest-download/googletest-prefix/src/release-1.8.1.zip'
     dst='~/Projects/Teaser-py/TEASER-plusplus/build/googletest-src'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 33%] No update step for 'googletest'
[ 44%] No patch step for 'googletest'
[ 55%] No configure step for 'googletest'
[ 66%] No build step for 'googletest'
[ 77%] No install step for 'googletest'
[ 88%] No test step for 'googletest'
[100%] Completed 'googletest'
[100%] Built target googletest
CMake Deprecation Warning at build/googletest-src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at build/googletest-src/googlemock/CMakeLists.txt:42 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at build/googletest-src/googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found PythonInterp: ~/anaconda3/envs/teaser/bin/python (found version "3.6.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Projects/Teaser-py/TEASER-plusplus/build/pmc-download
Scanning dependencies of target pmc
[ 11%] Creating directories for 'pmc'
[ 22%] Performing download step (git clone) for 'pmc'
Cloning into 'pmc-src'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[ 33%] Performing update step for 'pmc'
[ 44%] No patch step for 'pmc'
[ 55%] No configure step for 'pmc'
[ 66%] No build step for 'pmc'
[ 77%] No install step for 'pmc'
[ 88%] No test step for 'pmc'
[100%] Completed 'pmc'
[100%] Built target pmc
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Projects/Teaser-py/TEASER-plusplus/build/tinyply-download
Scanning dependencies of target pmc
[ 11%] Creating directories for 'pmc'
[ 22%] Performing download step (git clone) for 'pmc'
Cloning into 'tinyply-src'...
Note: switching to '0b9fff8e8bd4d37256554fe40cf76b2f3134377b'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0b9fff8 silence CMP0048 warnings
[ 33%] Performing update step for 'pmc'
[ 44%] No patch step for 'pmc'
[ 55%] No configure step for 'pmc'
[ 66%] No build step for 'pmc'
[ 77%] No install step for 'pmc'
[ 88%] No test step for 'pmc'
[100%] Completed 'pmc'
[100%] Built target pmc
CMake Deprecation Warning at build/tinyply-src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
-- Generating done
-- Build files have been written to: ~/Projects/Teaser-py/TEASER-plusplus/build/spectra-download
Scanning dependencies of target spectral
[ 11%] Creating directories for 'spectral'
[ 22%] Performing download step (git clone) for 'spectral'
Cloning into 'spectra-src'...
Note: switching to '5c4fb1de050847988faaaaa50f60e7d3d5f16143'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5c4fb1d Use CMAKE_CURRENT_SOURCE/BINRARY_DIR for inclusion in other CMake projects
[ 33%] Performing update step for 'spectral'
[ 44%] No patch step for 'spectral'
[ 55%] No configure step for 'spectral'
[ 66%] No build step for 'spectral'
[ 77%] No install step for 'spectral'
[ 88%] No test step for 'spectral'
[100%] Completed 'spectral'
[100%] Built target spectral
-- Failed to find sphinx-build executable (missing: SPHINX_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Projects/Teaser-py/TEASER-plusplus/build/pybind11-download
Scanning dependencies of target pmc
[ 11%] Creating directories for 'pmc'
[ 22%] Performing download step (git clone) for 'pmc'
Cloning into 'pybind11-src'...
Note: switching to 'v2.4.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 80d4524 v2.4.3 release
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
Cloning into '~/Projects/Teaser-py/TEASER-plusplus/build/pybind11-src/tools/clang'...
Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
[ 33%] Performing update step for 'pmc'
[ 44%] No patch step for 'pmc'
[ 55%] No configure step for 'pmc'
[ 66%] No build step for 'pmc'
[ 77%] No install step for 'pmc'
[ 88%] No test step for 'pmc'
[100%] Completed 'pmc'
[100%] Built target pmc
-- Found PythonInterp: ~/anaconda3/envs/teaser/bin/python (found suitable version "3.6.12", minimum required is "3.6") 
-- Found PythonLibs: ~/anaconda3/envs/teaser/lib/libpython3.6m.so
-- pybind11 v2.4.3
-- TEASER++ Python binding will be built.
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Python Interpreter Version: 3.6
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Projects/Teaser-py/TEASER-plusplus/build
Scanning dependencies of target pmc
[  6%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_heu.cpp.o
[ 13%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_maxclique.cpp.o
[ 20%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmcx_maxclique.cpp.o
[ 26%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmcx_maxclique_basic.cpp.o
[ 33%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_cores.cpp.o
[ 40%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_utils.cpp.o
[ 46%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_graph.cpp.o
[ 53%] Building CXX object pmc-build/CMakeFiles/pmc.dir/pmc_clique_utils.cpp.o
[ 60%] Linking CXX shared library libpmc.so
[ 60%] Built target pmc
Scanning dependencies of target teaser_registration
[ 66%] Building CXX object teaser/CMakeFiles/teaser_registration.dir/src/certification.cc.o
[ 73%] Building CXX object teaser/CMakeFiles/teaser_registration.dir/src/registration.cc.o
[ 80%] Building CXX object teaser/CMakeFiles/teaser_registration.dir/src/graph.cc.o
[ 86%] Linking CXX shared library libteaser_registration.so
[ 86%] Built target teaser_registration
Scanning dependencies of target teaserpp_python
[ 93%] Building CXX object python/CMakeFiles/teaserpp_python.dir/teaserpp_python/teaserpp_python.cc.o
[100%] Linking CXX shared module teaserpp_python/teaserpp_python.cpython-36m-x86_64-linux-gnu.so
[100%] Built target teaserpp_python
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/build$ cd python && pip install .
Processing ~/Projects/Teaser-py/TEASER-plusplus/build/python
Building wheels for collected packages: teaserpp-python
  Building wheel for teaserpp-python (setup.py) ... done
  Created wheel for teaserpp-python: filename=teaserpp_python-1.0.0-py3-none-any.whl size=109654 sha256=730f316a864ce85d985b4239cd18741786d024140024e66249b37e934b6d85d1
  Stored in directory: /tmp/pip-ephem-wheel-cache-cyijc0yo/wheels/1e/bf/63/70a02cd0346a7ca45a67e1a5fcf8e44b28b2b766fa571cb7f7
Successfully built teaserpp-python
Installing collected packages: teaserpp-python
Successfully installed teaserpp-python-1.0.0
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/build/python$ cd ../.. && cd examples/teaser_python_3dsmooth
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/examples/teaser_python_3dsmooth$ python teaser_python_3dsmooth.py
Traceback (most recent call last):
  File "teaser_python_3dsmooth.py", line 4, in <module>
    import line_mesh
  File "~/Projects/Teaser-py/TEASER-plusplus/examples/teaser_python_3dsmooth/line_mesh.py", line 4, in <module>
    import open3d as o3d
  File "~/.local/lib/python3.6/site-packages/open3d/__init__.py", line 103, in <module>
    import open3d.ml
  File "~/.local/lib/python3.6/site-packages/open3d/ml/__init__.py", line 35, in <module>
    from . import datasets
  File "~/.local/lib/python3.6/site-packages/open3d/ml/datasets.py", line 34, in <module>
    from open3d._ml3d.datasets import *
  File "~/.local/lib/python3.6/site-packages/open3d/_ml3d/datasets/__init__.py", line 6, in <module>
    from .s3dis import S3DIS
  File "~/.local/lib/python3.6/site-packages/open3d/_ml3d/datasets/s3dis.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/examples/teaser_python_3dsmooth$ conda install pandas
Collecting package metadata (current_repodata.json): done
Solving environment: done

** Package Plan **

  environment location: ~/anaconda3/envs/teaser

  added / updated specs:
    - pandas


The following NEW packages will be INSTALLED:

  pandas             pkgs/main/linux-64::pandas-1.1.3-py36he6710b0_0
  pytz               pkgs/main/noarch::pytz-2020.5-pyhd3eb1b0_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/examples/teaser_python_3dsmooth$ python teaser_python_3dsmooth.py
Traceback (most recent call last):
  File "teaser_python_3dsmooth.py", line 4, in <module>
    import line_mesh
  File "~/Projects/Teaser-py/TEASER-plusplus/examples/teaser_python_3dsmooth/line_mesh.py", line 4, in <module>
    import open3d as o3d
  File "~/.local/lib/python3.6/site-packages/open3d/__init__.py", line 103, in <module>
    import open3d.ml
  File "~/.local/lib/python3.6/site-packages/open3d/ml/__init__.py", line 35, in <module>
    from . import datasets
  File "~/.local/lib/python3.6/site-packages/open3d/ml/datasets.py", line 34, in <module>
    from open3d._ml3d.datasets import *
  File "~/.local/lib/python3.6/site-packages/open3d/_ml3d/datasets/__init__.py", line 6, in <module>
    from .s3dis import S3DIS
  File "~/.local/lib/python3.6/site-packages/open3d/_ml3d/datasets/s3dis.py", line 7, in <module>
    from plyfile import PlyData, PlyElement
ModuleNotFoundError: No module named 'plyfile'
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/examples/teaser_python_3dsmooth$ conda install -c conda-forge plyfile
Collecting package metadata (current_repodata.json): done
Solving environment: done

** Package Plan **

  environment location: ~/anaconda3/envs/teaser

  added / updated specs:
    - plyfile


The following NEW packages will be INSTALLED:

  plyfile            conda-forge/noarch::plyfile-0.7.2-pyh9f0ad1d_0
  python_abi         conda-forge/linux-64::python_abi-3.6-1_cp36m

The following packages will be UPDATED:

  certifi            pkgs/main::certifi-2020.12.5-py36h06a~ --> conda-forge::certifi-2020.12.5-py36h5fab9bb_1

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2021.1.19-~ --> conda-forge::ca-certificates-2020.12.5-ha878542_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(teaser) ~/Projects/Teaser-py/TEASER-plusplus/examples/teaser_python_3dsmooth$ python teaser_python_3dsmooth.py
==================================================
        TEASER++ Python registration example      
==================================================
Traceback (most recent call last):
  File "teaser_python_3dsmooth.py", line 345, in <module>
    scene_path, desc_path, gt_mat, pair[0], pair[1]
  File "teaser_python_3dsmooth.py", line 267, in pair_eval_helper
    frag1 = o3d.registration.Feature()
AttributeError: module 'open3d' has no attribute 'registration'

````

**Comment by jingnanshi** [comment]
Hi @hamid54 , thank you for your interest. Can you try with open3d version = 0.10.0?

**Comment by hamid54** [comment]
Hi, @jingnanshi thank you for the response! 
I tried with open3d 0.10.0, but nothing changed.

**Comment by jingnanshi** [comment]
@hamid54 try 0.9.0.0. This should work.

**Comment by hamid54** [comment]
@jingnanshi the first try was 0.9.0.0. Then, after your previous comment, I tried 0.0.10. The result did not change and the error message was the same. Thank you!

**Comment by jingnanshi** [comment]
@hamid54 please check again whether you have actually installed open3d 0.9 correctly. On my machine both 0.9 and 0.10 has module registration

**Comment by Dostoyewski** [comment]
It will work with the latest version of Open3D.
